name = "LazIO"
uuid = "c3605908-9f0f-11e8-0a72-0d361c15a277"
authors = ["Maarten Pronk <git@evetion.nl>"]
version = "0.1.3"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
LasIO = "570499db-eae3-5eb6-bdd5-a5326f375e68"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinaryProvider = "0.5"
FileIO = "1.2"
FixedPointNumbers = "0.5, 0.6, 0.7, 0.8"
LasIO = "0.3"
Parameters = "0.12"
Tables = "0.2"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
